### PR TITLE
Rework tooling docs

### PR DESCRIPTION
**Pull request by roll**
Hi @lwinfree @rufuspollock @sglavoie,

It's an initial work towards the new structure of the docs that I proposed at the meeting. It already includes `frictionless-py`'s docs and other lower-level docs e.g. for JS

For review simplicity, I've deployed a staging - https://fd.roll1.vercel.app

**The only change is the "Tooling" section.**

### CODE REVIEW

**Comment by lwinfree** [comment]
I think I like these changes @roll! I definitely like the division into languages in the menu

**Comment by rufuspollock** [comment]
Generally looks good. Some minor comments e.g. "Drivers" maybe vs SDKs but this is stuff we can look at when ready to merge (or tweak later).

**Comment by roll** [comment]
If there is a documentation sprint in coming weeks we can build on top of this draft

**Comment by roll** [comment]
Somehow the url has been changed on the last deploy. The newer version (still very draft) - https://fd.roll1.vercel.app/tooling/python/#purpose

**Comment by roll** [comment]
Hi @lwinfree,

It's ready for a review

**Comment by roll** [comment]
https://fd-delta.vercel.app/

**Review by lwinfree — APPROVED** [review]
this looks really good, thanks! merging now & then we can iterate on this improvement.

**Pull request merged**
