### PR TITLE
Improve software and standards pages

### PR DESCRIPTION
**Pull request by roll**
# Overview

It's been built on top of the discussion in https://github.com/frictionlessdata/website/pull/203

- https://staging.frictionlessdata.io/software/
- https://staging.frictionlessdata.io/standards/

---

The idea is not to solve the unsolvable problem of grouping our software and standards. But to provide guides of using it with end-user skills or needs-related structuring. It creates kind a map/instruction like "How to use Software / Where to start". The exact tests are very raw - I just wanted to have it conceptually finished.

---

Also, updated the main page pictures :+1:

toolkit

### CODE REVIEW

**Comment by roll** [comment]
@lwinfree 
I really like your text addition in https://github.com/frictionlessdata/website/pull/203.

If you think adding Software Guide makes sense do you think it's possible to integrate your addition somewhere into the guide?

**Comment by lwinfree** [comment]
alright @roll I edited the text on the software page! I still need to look at the specs page - I'll do that tomorrow. This is looking really good IMO!

**Comment by roll** [comment]
Great @lwinfree! I like your 3 ways separation for software. I've added a few small tweaks and deployed to staging

**Comment by lwinfree** [comment]
hey @roll I just edited the standards text (though I wrote software in my commit message x_x). I also added the specs overview pic from the specs site at the bottom. I didn't style it at all - it is a bit big maybe? I thought it was helpful to understand how the specs relate to each other. What do you think?

**Comment by roll** [comment]
@lwinfree 
Great! I added a few minor tweaks and merging :+1:

**Pull request merged**
