### PR TITLE
Added notebooks

### PR DESCRIPTION
**Pull request by roll**
- fixes https://github.com/frictionlessdata/project/issues/498

---

@lauragift21 @lwinfree 
Please review and decide where to place the output markdowns

---

http://localhost:8080/how-to/how-to-use-data-packages-with-pandas/
http://localhost:8080/how-to/how-to-use-data-packages-with-ckan/
http://localhost:8080/how-to/how-to-load-data-packages-into-bigquery/

### CODE REVIEW

**Comment by lauragift21** [comment]
Hi @roll. This looks good. I suggested adding a page listing out all the how-tos guide we have and link that in the nav under Learn. I tried embedding the `README.ipynb` file directly on the page but that did not work.

Screenshot 2020-05-21 at 12 38 08 PM

**Comment by roll** [comment]
@lauragift21 
I've added 'ipynb' to have copies of notebooks sources - not sure we need to add them to the site

**Comment by lauragift21** [comment]
Oh alright. then that's fine. Having a page to display all the how-tos a with a link to individual pages will be great.

**Comment by roll** [comment]
@lauragift21 
Would you like to merge and update based on your plan? The PR basically just adds a mechanism of retrieving and converting notebooks but you can manage them as you want

**Comment by lauragift21** [comment]
Yeah, sure I can @roll.

**Pull request merged**
