### PR TITLE
Add blog about Table Schema Frictionless Specs at the EU commission

### PR DESCRIPTION
**Pull request by sglavoie**
Cross-posting from https://github.com/datopian/frontend/pull/453 in case you would like to include this post. If you would like me to change anything, please let me know! :slightly_smiling_face: 

---

Please preserve this line to notify @lwinfree (lead of this repository)

### CODE REVIEW

**Comment by lwinfree** [comment]
Hi @sapetti9 ! If you have time, would you please read through this and give Sebastien edits if it needs any editing? When you are happy with it, please merge :-) thanks!

**Comment by sapetti9** [comment]
Hey @sglavoie thanks for that! I think the blog is good, we could add an intro, or just start with _Do you remember Costas Simatos? He introduced the Frictionless Data community to..."_ and maybe add a smoother closing? WDYT?

**Comment by sglavoie** [comment]
@sapetti9 I wholeheartedly agree with you! I will spice things up a bit and commit some updates soon :wink:.

**Comment by sglavoie** [comment]
@sapetti9 how about this new addition? :slightly_smiling_face:

**Comment by lwinfree** [comment]
Hi @sglavoie! Sara is off this week so I told her I would follow up for her :-) This looks great - thanks for the edits & for the content!

**Pull request merged**
