### PR TITLE
Minor text improvements to Application page

### PR DESCRIPTION
**Pull request by dcslagel**
#### Description:
Minor text improvements to Application page
- Iterate language describing the current information on this page
- Update link to use the https url
- Remove the 'managed solution' statement because it seems to
  duplicate the previous goodtables.io link

#### Testing:

- Verified that the https link `https://try.goodtables.io/` does exists.

Let me know if this change could be accepted (or rejected) or
needs some additional changes to be approved and merged.

Thank you,
DC

### CODE REVIEW

**Comment by lwinfree** [comment]
Hi @dcslagel thanks for the edits :-) The managed solution for goodtables is actually a separate solution to the previously mentioned goodtables. The 2 are: http://try.goodtables.io/ (single validation) & https://goodtables.io/ (continuous validation). This should probably be more explicit though since it was unclear for you. If you'd like to edit your PR, please go ahead & we'll review it again. Thanks!

**Comment by dcslagel** [comment]
Hi @lwinfree,  

Yep,  I'll edit this to restore the managed solution.  Yes, I still don't fully understand the distinction between the two, but clarifying that can be a follow up pull-request.

Thanks,
DC

**Comment by dcslagel** [comment]
Hi @lwinfree,

Commit 257f080 restores the managed solution option.  It also updates the managed solution link from the dead link `../others/goodtables`  to `https://goodtables.io`.

Let me know if additional changes are needed.

Thanks,
DC

**Comment by dcslagel** [comment]
Hi @lwinfree,  

Just following up on outstanding pull requests.  Let me know if additional changes are needed for this pull-request to be approved for merge.

Thank you,
DC

**Comment by dcslagel** [comment]
This branch has been rebased to be uptodate with the main branch.  Let me know if additional changes are needed for this pull-request to be approved for merge.

Thank you,
DC

**Comment by lwinfree** [comment]
thanks @dcslagel

**Pull request merged**
