### PR TITLE
add ISA² Interoperability Testbed to the adption page

### PR DESCRIPTION
**Pull request by augusto-herrmann**
# Overview

In 2019 I suggested to Costas Simatos and other contributors to the ISA² Interoperability Testbed (a project of the European Commission) that they could validate CSV files using the tabular data package specification from frictionless. In 2020 he wrote me back with the link to a working implementation [here](https://www.itb.ec.europa.eu/csv/any/upload).

I think this would count as adoption from the European Commission, so I made this PR to propose to add it to the [adoption page](https://frictionlessdata.io/adoption/). There is no blog post to link to, so perhaps would that case deserve a new blog post? If you want I can put you in touch with Costas Simatos.

---

Please preserve this line to notify @lwinfree (lead of this repository)

### CODE REVIEW

**Comment by augusto-herrmann** [comment]
BTW, they also have a public Docker image of this validator in [Docker Hub](https://hub.docker.com/r/isaitb/csv-validator) and also a [CSV Validating Gude](https://www.itb.ec.europa.eu/docs/guides/latest/validatingCSV/).

**Comment by lwinfree** [comment]
Hi @augusto-herrmann thank you for this! We actually do have a blog about this, but we had forgotten to add it to the adoption page, so this is a really nice PR! I'll add in the blog link & then merge :-)

**Comment by lwinfree** [comment]
ahh actually @augusto-herrmann could you add the link please?

It is this:  https://frictionlessdata.io/blog/2021/06/28/frictionless-specs-european-commission/ 

Thank you!

**Comment by augusto-herrmann** [comment]
I didn't know there was already a blog post about it.

Added!

**Pull request merged**
